### ISSUE TITLE
Does this work in 2019?

### ISSUE THREAD

**Issue by troys-code** [JustinFincher/WebViewTextureiOS#1]
Has anyone got it working in Unity 2019? Will try this out soon. There is often extra steps to get an older project to build.

Only Metal is needed these days, since Apple deprecated Open GL earlier this year.

**Comment by JustinFincher** [comment]
Hi, sorry for the late reply! I am not sure about its validity as both Unity and iOS have been updated much since then (especially now UIWebView is deprecated). I am considering rewrite this project using WKWebView and Unity 2019.3 after finishing my current Android project.
